import { discProfiles } from '../data/discQuestions';

// ── Logo ──────────────────────────────────────────────────────────────────────
const logoHtml = (white = false) => {
  const dark  = white ? '#FFFFFF' : '#1B5299';
  const light = white ? 'rgba(255,255,255,0.6)' : '#5BB8E4';
  return `<div style="display:flex;align-items:center;gap:8px">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 47 47" height="24" style="flex-shrink:0;display:block">
      <rect x="0"  y="0"  width="22" height="22" rx="2.5" fill="${dark}"/>
      <rect x="25" y="0"  width="22" height="22" rx="2.5" fill="${light}"/>
      <rect x="0"  y="25" width="22" height="22" rx="2.5" fill="${dark}"/>
      <rect x="25" y="25" width="22" height="22" rx="2.5" fill="${dark}"/>
    </svg>
    <div style="line-height:1">
      <div style="font-family:'Arial Black',Arial,sans-serif;font-weight:900;font-size:18px;color:${dark};letter-spacing:-0.4px;line-height:1.1">Wayzim</div>
      <div style="font-size:8px;color:${white?'rgba(255,255,255,0.5)':'#6B7280'};font-weight:600;letter-spacing:0.04em;margin-top:1px">People Report</div>
    </div>
  </div>`;
};

// ── Static UI labels ──────────────────────────────────────────────────────────
const L = {
  pt: {
    confidential:'DOCUMENTO CONFIDENCIAL', executiveReport:'Relatório Executivo de Candidato',
    recommendation:'Recomendação', technical:'Score Técnico', behavioral:'Score Comportamental',
    summary:'Parecer Qualitativo', strengths:'Pontos Fortes', gaps:'Gaps Identificados',
    risks:'Pontos de Atenção', candidateData:'Dados do Candidato', email:'E-mail',
    whatsapp:'WhatsApp', city:'Cidade', salary:'Pretensão Salarial', availability:'Disponibilidade',
    seniority:'Senioridade', linkedin:'LinkedIn', languages:'Idiomas', comments:'Comentários do Entrevistador',
    generatedBy:'Gerado pela Wayzim People Platform', page:'Página', of:'de',
    discProfile:'Perfil Comportamental DISC',
    recLabels:{ recommended:'Recomendado ✓', recommended_with_caveats:'Recomendado com Ressalvas ⚠', not_recommended:'Não Recomendado ✗' },
    discBehaviors:'Como este perfil se comporta no dia a dia',
    discCommunication:'Estilo de Comunicação', discLeadership:'Estilo de Liderança',
    discConflict:'Gestão de Conflito', discMotivators:'O que energiza este perfil',
    discDemotivators:'O que drena este perfil', discBlindSpots:'Pontos Cegos',
    discSecondary:'Influência do Perfil Secundário',
    dominance:'Dominância (D)', influence:'Influência (I)', stability:'Estabilidade (S)', conformity:'Conformidade (C)',
  },
  en: {
    confidential:'CONFIDENTIAL DOCUMENT', executiveReport:'Candidate Executive Report',
    recommendation:'Recommendation', technical:'Technical Score', behavioral:'Behavioral Score',
    summary:'Qualitative Summary', strengths:'Strengths', gaps:'Identified Gaps',
    risks:'Risk Points', candidateData:'Candidate Data', email:'Email',
    whatsapp:'WhatsApp', city:'City', salary:'Salary Expectation', availability:'Start Availability',
    seniority:'Seniority', linkedin:'LinkedIn', languages:'Languages', comments:'Interviewer Comments',
    generatedBy:'Generated by Wayzim People Platform', page:'Page', of:'of',
    discProfile:'DISC Behavioral Profile',
    recLabels:{ recommended:'Recommended ✓', recommended_with_caveats:'Recommended with Caveats ⚠', not_recommended:'Not Recommended ✗' },
    discBehaviors:'Day-to-day behavioral tendencies',
    discCommunication:'Communication Style', discLeadership:'Leadership Style',
    discConflict:'Conflict Management', discMotivators:'What energizes this profile',
    discDemotivators:'What drains this profile', discBlindSpots:'Blind Spots',
    discSecondary:'Secondary Profile Influence',
    dominance:'Dominance (D)', influence:'Influence (I)', stability:'Stability (S)', conformity:'Conformity (C)',
  },
  zh: {
    confidential:'机密文件', executiveReport:'候选人执行报告',
    recommendation:'推荐意见', technical:'技术评分', behavioral:'行为评分',
    summary:'定性总结', strengths:'优势', gaps:'差距分析',
    risks:'风险点', candidateData:'候选人信息', email:'电子邮件',
    whatsapp:'WhatsApp', city:'城市', salary:'薪资期望', availability:'入职时间',
    seniority:'资历', linkedin:'LinkedIn', languages:'语言能力', comments:'面试官意见',
    generatedBy:'由 Wayzim 人才平台自动生成', page:'第', of:'页，共',
    discProfile:'DISC 行为档案',
    recLabels:{ recommended:'推荐 ✓', recommended_with_caveats:'有条件推荐 ⚠', not_recommended:'不推荐 ✗' },
    discBehaviors:'日常行为倾向',
    discCommunication:'沟通风格', discLeadership:'领导风格',
    discConflict:'冲突处理', discMotivators:'激励因素',
    discDemotivators:'消极因素', discBlindSpots:'盲点',
    discSecondary:'次要档案影响',
    dominance:'支配型 (D)', influence:'影响型 (I)', stability:'稳定型 (S)', conformity:'谨慎型 (C)',
  },
};

const seniorityI18n = {
  pt:{ 'Sênior':'Sênior','Pleno':'Pleno','Júnior':'Júnior','Estágio/Trainee':'Estágio/Trainee' },
  en:{ 'Sênior':'Senior','Pleno':'Mid-level','Júnior':'Junior','Estágio/Trainee':'Internship/Trainee' },
  zh:{ 'Sênior':'高级','Pleno':'中级','Júnior':'初级','Estágio/Trainee':'实习/培训生' },
};

const stageI18n = {
  en:{ 'Triagem de Currículo':'CV Screening','Entrevista RH':'HR Interview','Entrevista Técnica':'Technical Interview','Entrevista com Liderança':'Leadership Interview','Assessment':'Assessment','Proposta':'Job Offer' },
  zh:{ 'Triagem de Currículo':'简历筛选','Entrevista RH':'HR面试','Entrevista Técnica':'技术面试','Entrevista com Liderança':'高管面试','Assessment':'评估','Proposta':'录用通知' },
};

const langNameI18n = {
  en:{ 'Inglês':'English','Espanhol':'Spanish','Francês':'French','Alemão':'German','Italiano':'Italian','Mandarim':'Mandarin','Japonês':'Japanese','Árabe':'Arabic','Português':'Portuguese' },
  zh:{ 'Inglês':'英语','Espanhol':'西班牙语','Francês':'法语','Alemão':'德语','Italiano':'意大利语','Mandarim':'普通话','Japonês':'日语','Árabe':'阿拉伯语','Português':'葡萄牙语' },
};

const langLevelI18n = {
  en:{ 'Básico':'Basic','Intermediário':'Intermediate','Avançado':'Advanced','Fluente':'Fluent','Nativo':'Native' },
  zh:{ 'Básico':'基础','Intermediário':'中级','Avançado':'高级','Fluente':'流利','Nativo':'母语' },
};

const recColors = {
  recommended:             { bg:'#ECFDF5', color:'#065F46', border:'#10B981' },
  recommended_with_caveats:{ bg:'#FFFBEB', color:'#92400E', border:'#F59E0B' },
  not_recommended:         { bg:'#FEF2F2', color:'#991B1B', border:'#EF4444' },
};

const discColors = {
  D:{ color:'#EF4444', bg:'#FEF2F2', emoji:'🔴' },
  I:{ color:'#F59E0B', bg:'#FFFBEB', emoji:'🟡' },
  S:{ color:'#10B981', bg:'#ECFDF5', emoji:'🟢' },
  C:{ color:'#3B82F6', bg:'#EFF6FF', emoji:'🔵' },
};

// ── Full DISC content per language ────────────────────────────────────────────
// PT: pulled from discProfiles (discQuestions.js)
// EN / ZH: defined here
const discContentI18n = {
  en: {
    D: {
      title:'Executor', subtitle:'Results-Oriented | Direct | Decisive',
      summary:'Driven by challenges and tangible results. Natural leader, makes quick decisions, prefers dynamic environments with full autonomy. Seeks efficiency above all and does not tolerate processes that add no value.',
      strengths:['Decision-making capacity','Results orientation','Leadership under pressure','Focus and objectivity'],
      behaviors:[
        { icon:'⚡', title:'Under deadline pressure', text:'Increases pace, delegates what they can, and focuses entirely on results. Does not stop to process emotions — acts immediately. Can become terse and impatient with colleagues who need more time. In crises, naturally takes command even without being designated.' },
        { icon:'🎯', title:'In decision-making meetings', text:'The first to propose a solution and push for closure. Detests meetings without a final decision. If the conversation goes in circles, will interrupt and demand objectivity. May be perceived as domineering, but the impulse is purely pragmatic.' },
        { icon:'⚔️', title:'When they disagree', text:'States their point of view without hesitation, directly and sometimes abruptly. Does not soften criticism. This can generate friction with more sensitive profiles, but they see it as clarity, not conflict. Resolves quickly and moves on without holding grudges.' },
        { icon:'🔄', title:'Facing changes', text:'Embraces changes if they make sense for the result. Feels no nostalgia for old processes. Can change direction quickly without needing the team\'s emotional validation, which may generate insecurity in colleagues who need more adaptation time.' },
        { icon:'📣', title:'Giving and receiving feedback', text:'Prefers direct feedback without protocol. When receiving, wants to know exactly what to change — not the emotional impact on others. When giving, may be more honest than tactful, requiring care when the recipient has an S or I profile.' },
      ],
      communication:{ style:'Direct, objective, action-oriented. Gets straight to the point without long introductions.', tips:[
        '"We need X by Friday" — not "it would be great if we could think about…"',
        'Short messages. Does not respond well to long emails without a clear conclusion.',
        'In presentations, wants the result first — then details only if needed.',
        'Does not need agreement, but needs you to be direct.',
      ]},
      leadership:'Leads by example through delivery speed. Expects the team to keep pace. Delegates tasks but struggles to delegate control. In a crisis, naturally takes command even without being designated.',
      conflict:'Goes directly to the point of disagreement without prolonging it. Resolves quickly and moves on — holds no grudges. May escalate if they feel ignored or if the conversation leads nowhere.',
      motivators:['Full autonomy to execute','Ambitious goals and growing challenges','Recognition for concrete results','Fast growth and visible impact'],
      demotivators:['Micromanagement and excessive approval chains','Slow processes without justification','Meetings without agenda or decision','Environment without clear meritocracy'],
      blindSpots:['May make decisions too quickly without listening to the team — and pay the price later.','Underestimates the emotional impact of direct words on S and I profiles.','May treat relationships as transactional, weakening bonds needed for execution.','Impatience with details can generate operational errors that need correction.'],
    },
    I: {
      title:'Communicator', subtitle:'Enthusiastic | Sociable | Persuasive',
      summary:'Contagious energy and a natural ability to engage people. Optimistic, creative, thrives in collaborative environments. Brings motivation and lightness to the team. When motivated, elevates the entire environment.',
      strengths:['Communication and persuasion','Creativity','Team engagement','Interpersonal relationships'],
      behaviors:[
        { icon:'💡', title:'In brainstorming sessions', text:'Warms up the room, encourages quieter members to speak, and connects ideas from different sources. Often the center of creative dynamics. May generate many ideas without filtering viability — depth comes with C and D partnerships.' },
        { icon:'🌟', title:'Motivated vs. demotivated', text:'When motivated, is a force of engagement — the team feels it. When demotivated, the environment also feels it: becomes quiet, scattered, and low-energy. This profile\'s mood has direct impact on team climate, positively or negatively.' },
        { icon:'🤝', title:'Building relationships', text:'Creates connections quickly and naturally. Remembers names, personal details, and birthdays. This builds enormous social capital — but may be perceived as superficiality if not backed by consistent delivery.' },
        { icon:'⏰', title:'With deadlines and deliveries', text:'Natural optimism causes underestimation of time required for tasks. May promise more than they deliver — not from bad faith, but from overconfidence. Works better with frequent checkpoints and clear intermediate deadlines.' },
        { icon:'🗣️', title:'Handling conflict', text:'Avoids direct confrontation at all costs. Prefers resolving through informal conversation. May hold resentments instead of expressing them — and when they finally do, it may come with accumulated intensity.' },
      ],
      communication:{ style:'Fluid, engaging, with stories and personal examples. Naturally adapts the message to the audience.', tips:[
        'Uses narratives and analogies to persuade — facts alone do not motivate them.',
        'Responds well to explicit recognition and public praise, especially before a request.',
        'May be perceived as "meandering" by D and C profiles — needs discipline to be more concise.',
        'Prefers in-person or voice communication — tends to ignore long emails.',
      ]},
      leadership:'Leads by inspiring. Creates a sense of purpose, enthusiasm, and belonging. Most effective in situations requiring mobilization and team engagement. May struggle with difficult decisions involving conflict or cutting people.',
      conflict:'Avoids direct confrontation at all costs. Prefers to soften and seek consensus. When pressured, may verbally agree without internally changing — or unexpectedly explode from accumulated pressure.',
      motivators:['Frequent and public recognition','Teamwork and social interaction','Variety, creativity, and constant novelty','Freedom of expression and space to influence'],
      demotivators:['Isolation and solitary work for extended periods','Repetitive tasks without human interaction','No recognition even with good delivery','Overly rigid rules with no room for improvisation'],
      blindSpots:['May start many projects enthusiastically and finish none with depth.','Excess optimism generates promises beyond actual delivery capacity.','Difficulty with detail work requiring repetitive precision and discipline.','May prioritize the relationship over the result — hesitating to give difficult feedback.'],
    },
    S: {
      title:'Stabilizer', subtitle:'Patient | Reliable | Collaborative',
      summary:'The foundation of any team. Brings consistency, loyalty, and a unique ability to create harmony. Prefers predictable environments and is deeply dedicated to what they take on. The person everyone can count on — always.',
      strengths:['Reliability','Conflict management','Consistency','Empathy and active listening'],
      behaviors:[
        { icon:'🕊️', title:'In moments of tension', text:'Naturally assumes the mediator role. Listens to both sides without judgment, seeks solutions that preserve relationships. In polarized teams, prevents conflict from escalating. This is immensely valuable — but may cause them to postpone difficult conversations too long.' },
        { icon:'📋', title:'With role clarity', text:'Needs to receive assignments clearly before starting. Ambiguity about expectations generates real anxiety. When well-oriented, delivers with exemplary consistency. When scope changes without explanation, may freeze or act with insecurity.' },
        { icon:'🔄', title:'Facing changes', text:'Processes changes more slowly than other profiles — not from passive resistance, but because they need to understand the reason before committing. When change is well explained and conducted with empathy, adapts completely. When imposed by surprise, may silently disengage.' },
        { icon:'💬', title:'Saying "no"', text:'Has enormous difficulty refusing requests, even when already overloaded. May say "yes" verbally and "no" passively — procrastinating, forgetting, or avoiding delivery. The key is creating a safe environment where expressing limits is encouraged.' },
        { icon:'🤗', title:'As a team partner', text:'Loyal to people and projects. May remain in a bad situation longer than they should, driven by commitment and fear of disappointing. Consistently places the team\'s wellbeing above their own to a concerning degree.' },
      ],
      communication:{ style:'Listens far more than they speak. Soft, empathetic communication, careful with words.', tips:[
        'Prefers private conversations to public debates — becomes defensive when confronted in front of others.',
        'When delivering bad news, seeks the gentlest way, which can dilute the clarity of the message.',
        'Takes time to express strong opinions — but when they do, it is because they truly believe it.',
        'Responds well when the interlocutor shows genuine interest in listening, not just persuading.',
      ]},
      leadership:'Leads through service and availability. Always present to help the team. Naturally creates a culture of collaboration and psychological safety. May struggle establishing authority in open conflict situations.',
      conflict:'Avoids conflict at all costs — sometimes for too long. When directly confronted, may go silent or externally agree without internally changing. Resolves best in a calm environment, without pressure, with time to process.',
      motivators:['Stable, predictable environment without constant surprises','Solid, long-term relationships with the team','Clarity about expectations and recognition for consistency','Feeling that their work matters to the people around them'],
      demotivators:['Sudden changes without explanation or empathy','Open conflicts and constant high-pressure environments','Ambiguity about role, scope, and expectations','Feeling used or undervalued despite consistent contribution'],
      blindSpots:['May yield too much to keep the peace — sacrificing their own interests and boundaries.','Silent resistance to change may be interpreted as lack of initiative or apathy.','Accumulates dissatisfaction without verbalizing — until reaching the limit unexpectedly.','Difficulty confronting poor performance from close colleagues, even when necessary.'],
    },
    C: {
      title:'Analyst', subtitle:'Precise | Systematic | Perfectionist',
      summary:'Analytical mind with an obsession for quality. Analyzes deeply before acting. High delivery standards and excels in environments that value rigor, processes, and technical excellence.',
      strengths:['Analytical thinking and critical reasoning','Attention to detail','Rigor and quality','Systematic planning'],
      behaviors:[
        { icon:'📊', title:'In fast decisions', text:'Needs sufficient data before committing. In meetings requiring instant decisions, may be the one who "slows" the process by requesting more analysis. This can be valuable (preventing errors) or costly (missing timing). Needs to learn to decide with partial information.' },
        { icon:'🔍', title:'Facing errors', text:'When they identify an error in a process — theirs or someone else\'s — they cannot ignore it. Must correct it, even if others perceive it as "minor." This generates high quality but may create friction with D profiles who prefer "good enough and fast."' },
        { icon:'📝', title:'Documentation and processes', text:'Their presentations, documents, and reports have above-average detail. This is a real differentiator, but may be excessive for interlocutors who prefer synthesis. Spontaneously creates robust processes — and is uncomfortable when others do not follow them.' },
        { icon:'🤐', title:'In open discussions', text:'Does not express opinions until certain they are correct. In debates where others speak quickly, may appear distant, passive, or without opinion. In reality, they are processing. When they finally speak, they typically bring the room\'s most solid argument.' },
        { icon:'💼', title:'Receiving feedback', text:'May take professional criticism very personally, especially about work quality — which is central to their identity. Needs specific, data-based feedback without personal judgment. Vague feedback ("it could have been better") paralyzes them.' },
      ],
      communication:{ style:'Precise, fact-based, data-driven. Avoids generalizations. Prefers writing over speaking.', tips:[
        'Prefers written communication — record-keeping, clarity, and ability to review.',
        'May be perceived as cold or distant by I and S profiles who expect warmth.',
        'Dislikes unsupported statements — "everyone knows that…" genuinely bothers them.',
        'In presentations, starts with data and arrives at the conclusion — opposite of D and I preference.',
      ]},
      leadership:'Leads through knowledge and the quality standard they establish. Inspires through technical mastery. May struggle giving autonomy without supervision. Excellent at creating processes, standards, and controls that elevate overall team quality.',
      conflict:'Prefers resolving with logical arguments and data — emotion does not persuade them and causes discomfort. May take criticism personally even when purely professional. In open conflict, tends to shut down, process alone, and avoid direct confrontation.',
      motivators:['Recognition for expertise and technical competency','Autonomy to do things right, without pressure for shortcuts','Organized environment with clear processes and high standards','Intellectually complex challenges requiring depth'],
      demotivators:['Pressure to deliver without quality — "done is better than perfect"','Decisions without solid grounding or based on pure intuition','Superficial work and colleagues who do not care about details','Process changes without consistent logical explanation'],
      blindSpots:['Analysis paralysis: may delay deliveries by being unable to stop perfecting.','Difficulty accepting that "good enough now" sometimes surpasses "perfect but late."','May negatively judge colleagues with different quality standards — generating friction.','Excessive focus on detail may cause them to lose sight of the bigger strategic context.'],
    },
  },
  zh: {
    D: {
      title:'执行者', subtitle:'以结果为导向 | 直接 | 果断',
      summary:'以挑战和切实成果为驱动力，天然的领导者，做出快速决策，偏好拥有完全自主权的动态环境。以效率为优先，不容忍无价值的流程。',
      strengths:['决策能力','成果导向','高压下的领导力','专注与客观'],
      behaviors:[
        { icon:'⚡', title:'在截止日期压力下', text:'加快节奏，尽可能委派任务，全力聚焦于结果。不会停下来处理情绪——直接行动。可能对需要更多时间的同事变得简短、不耐烦。在危机中，即使未被指定，也会自然承担指挥职责。' },
        { icon:'🎯', title:'在决策会议中', text:'第一个提出解决方案并推动结束讨论。不喜欢没有最终决定的会议。如果对话陷入循环，会打断并要求专注目标。可能被视为强势，但出发点纯粹是务实的。' },
        { icon:'⚔️', title:'当有不同意见时', text:'直接且毫不犹豫地表达观点，有时显得突兀。不会软化批评。这可能与敏感型人格产生摩擦，但他们将其视为清晰而非冲突。快速解决并继续前进，不记仇。' },
        { icon:'🔄', title:'面对变化时', text:'如果变化对结果有意义，会积极拥抱。对旧流程没有留恋。可以迅速改变方向，无需团队情感认可，这可能让需要更多适应时间的同事感到不安。' },
        { icon:'📣', title:'给予和接收反馈时', text:'偏好直接反馈，无需繁文缛节。接收反馈时，只想知道需要改变什么，而非情感影响。给予反馈时，可能比委婉更诚实，与S或I型人格交流时需特别注意。' },
      ],
      communication:{ style:'直接、客观、以行动为导向。直奔主题，不做冗长铺垫。', tips:[
        '偏好"我们需要在周五前完成X"而非"如果我们能考虑一下……"',
        '简短消息。不善于回应没有明确结论的长邮件。',
        '演示时，先要结果——再根据需要提供细节。',
        '不需要你同意，但需要你直接表达。',
      ]},
      leadership:'通过交付速度和执行力以身作则。期望团队跟上自己的节奏。委派任务但难以委派控制权。危机中，即使未被指定，也会自然接管指挥。',
      conflict:'直接切入分歧点，不拖延。快速解决并继续前进——不记仇。如果感到被忽视或对话没有结果，可能会升级冲突。',
      motivators:['完全的执行自主权','雄心勃勃的目标和不断增长的挑战','对具体成果的认可','快速成长和可见的影响力'],
      demotivators:['微观管理和过多审批环节','没有明确理由的缓慢流程','没有议程或决定的会议','没有明确绩效标准的环境'],
      blindSpots:['可能决策过快而不听取团队意见——事后付出代价。','低估直接措辞对S和I型人格的情感影响。','可能将关系视为功利性的，削弱执行所需的纽带。','对细节的不耐烦可能导致需要纠正的操作错误。'],
    },
    I: {
      title:'沟通者', subtitle:'热情 | 善于交际 | 有说服力',
      summary:'具有感染力的能量和天然的人际吸引力。乐观、富有创意，在协作环境中表现出色。为团队带来动力和活力。积极时，能提升整个团队的氛围。',
      strengths:['沟通与说服力','创造力','团队参与度','人际关系建立'],
      behaviors:[
        { icon:'💡', title:'在头脑风暴中', text:'活跃气氛，鼓励安静的成员发言，连接不同来源的想法。通常是创意动态的中心。可能产生许多未经可行性过滤的想法——深度需要与C和D型合作来实现。' },
        { icon:'🌟', title:'积极与消极状态对比', text:'积极时，是团队参与度的驱动力——整个团队都能感受到。消极时，环境也会感受到：变得安静、分散，能量低落。这种档案的情绪对团队氛围有直接影响，无论正面还是负面。' },
        { icon:'🤝', title:'建立关系', text:'快速自然地建立联系。记住名字、个人细节和生日。这积累了巨大的社会资本——但如果没有持续交付支撑，可能被视为肤浅。' },
        { icon:'⏰', title:'面对截止日期和交付', text:'天生的乐观导致低估任务所需时间。可能承诺超出实际交付能力的内容——不是出于恶意，而是过度自信。在频繁检查点和明确中间截止日期的环境中效果更佳。' },
        { icon:'🗣️', title:'处理冲突', text:'尽一切力量避免直接对抗。偏好通过非正式交谈解决。可能积压不满而不表达——当最终爆发时，可能带着积累的强度超出预期。' },
      ],
      communication:{ style:'流畅、引人入胜，用故事和个人例子表达。自然地将信息适应受众。', tips:[
        '用叙事和类比来说服——单纯的事实不能激励他们。',
        '对明确的认可和公开表扬反应良好，尤其是在请求之前。',
        '可能被D和C型视为"冗长"——需要自律来更简洁。',
        '偏好面对面或语音交流——倾向于忽略长邮件。',
      ]},
      leadership:'通过激励来领导。创造使命感、热情和归属感。在需要动员和团队参与的情况下最为有效。可能在涉及冲突或人员削减的艰难决策中挣扎。',
      conflict:'尽一切可能避免直接对抗。偏好缓和并寻求共识。在压力下，可能口头同意而内心不变——或因积累压力而出乎意料地爆发。',
      motivators:['频繁而公开的认可','团队合作和社交互动','多样性、创意和持续的新鲜感','表达自由和影响的空间'],
      demotivators:['长期独自工作和孤立','没有人际互动的重复性任务','即使交付良好也没有认可','过于死板的规则，没有即兴发挥的空间'],
      blindSpots:['可能满腔热情地启动许多项目，却没有深度完成任何一个。','过度乐观产生超出实际交付能力的承诺。','难以处理需要重复精确度和纪律的细节工作。','可能将关系置于结果之上——在给予困难反馈时犹豫不决。'],
    },
    S: {
      title:'稳定者', subtitle:'耐心 | 可靠 | 协作',
      summary:'是任何团队的基石。带来一致性、忠诚度和独特的创造和谐能力。偏好可预测的环境，对所承担的工作有深度投入。是每个人都可以依赖的人——始终如此。',
      strengths:['可靠性','冲突管理','一致性','同理心和积极倾听'],
      behaviors:[
        { icon:'🕊️', title:'在紧张时刻', text:'自然承担调解者角色。不带评判地倾听双方，寻求保护关系的解决方案。在两极化的团队中，防止冲突升级。这极具价值——但可能导致拖延过久才进行困难的对话。' },
        { icon:'📋', title:'对角色清晰度的需求', text:'开始前需要明确接收任务。对期望的模糊性会产生真实的焦虑。当指导明确时，交付的一致性堪称典范。当范围未加解释地改变时，可能会冻结或以不安全感行动。' },
        { icon:'🔄', title:'面对变化', text:'比其他档案更慢地处理变化——不是被动抗拒，而是需要在承诺之前理解原因。当变化得到充分解释并以同理心推进时，会完全适应。当突然强加时，可能会默默脱离参与。' },
        { icon:'💬', title:'说"不"', text:'即使已经超负荷，也极难拒绝请求。可能口头说"是"而被动地说"不"——拖延、忘记或回避交付。关键是创造一个鼓励表达边界的安全环境。' },
        { icon:'🤗', title:'作为团队伙伴', text:'对人和项目忠诚。可能在糟糕的情况下停留比应该更长的时间，出于承诺感和对让人失望的恐惧。持续将团队的福祉置于自身之上，程度令人担忧。' },
      ],
      communication:{ style:'倾听远多于表达。柔和、富有同理心的沟通，对措辞谨慎。', tips:[
        '偏好私下交谈而非公开辩论——当着他人面被对抗时会进入防御状态。',
        '传递坏消息时，寻求最温和的方式，这可能稀释信息的清晰度。',
        '需要时间表达强烈意见——但当他们表达时，是因为真正相信。',
        '当对方表现出真正倾听的兴趣而非仅仅说服时，反应良好。',
      ]},
      leadership:'通过服务和可用性来领导。始终在场帮助团队。自然地创造协作文化和心理安全。在公开冲突情况下可能难以建立权威。',
      conflict:'尽一切力量避免冲突——有时过于长久。被直接对抗时，可能沉默或口头同意而内心不变。在平静环境中、不受压力、有时间处理的情况下解决最佳。',
      motivators:['稳定、可预期的环境，没有持续的意外','与团队的稳固长期关系','对期望的清晰认识和对一致性的认可','感到自己的工作对周围的人重要'],
      demotivators:['没有解释或同理心的突然变化','公开冲突和持续高压环境','对角色、范围和期望的模糊','尽管持续贡献却感到被使用或不被重视'],
      blindSpots:['可能为了维持和平而过度退让——牺牲自己的利益和边界。','对变化的沉默抵制可能被解读为缺乏主动性或冷漠。','积累不满而不表达——直到出乎意料地达到极限。','难以面对亲密同事的表现问题，即使在必要时也是如此。'],
    },
    C: {
      title:'分析师', subtitle:'精确 | 系统化 | 完美主义',
      summary:'拥有分析型思维和对质量的执着。行动之前进行深度分析。交付标准极高，在重视严谨、流程和技术卓越的环境中脱颖而出。',
      strengths:['分析与批判性思维','注重细节','严谨与质量','系统化规划'],
      behaviors:[
        { icon:'📊', title:'在快速决策中', text:'在承诺之前需要足够的数据。在需要当场做出决定的会议中，可能是"减缓"流程要求更多分析的人。这可能有价值（防止错误）或代价高昂（错过时机）。需要学会在不完整信息下做出决定。' },
        { icon:'🔍', title:'面对错误', text:'当发现流程中的错误——无论是自己的还是他人的——都无法忽视。必须纠正，即使其他人认为这是"小"错误。这产生高质量，但可能与偏好"足够好就快"的D型产生摩擦。' },
        { icon:'📝', title:'文档和流程', text:'他们的演示、文档和报告的详细程度高于平均水平。这是真正的优势，但对于偏好简洁的听众可能过于详细。自发地创建健壮的流程——当他人不遵循时会感到不适。' },
        { icon:'🤐', title:'在公开讨论中', text:'在确定自己正确之前不表达意见。在他人快速发言的辩论中，可能显得疏离、被动或没有意见。实际上，他们正在处理信息。当他们最终发言时，通常带来全场最有力的论点。' },
        { icon:'💼', title:'接收反馈时', text:'可能将专业批评非常个人化，尤其是关于工作质量——这是他们身份认同的核心。需要具体的、基于数据的、不带个人判断的反馈。模糊的反馈（"可以更好"）会让他们停滞不前。' },
      ],
      communication:{ style:'精确、基于事实和数据。避免泛化。偏好书写胜于口头表达。', tips:[
        '偏好书面沟通——记录、清晰和可审查的能力。',
        '可能被I和S型视为冷漠或疏离，因为这些类型期望更多人情味。',
        '不喜欢无证据的陈述——"大家都知道……"真的让他们感到烦恼。',
        '演示时，从数据开始到结论结束——与D和I偏好的相反。',
      ]},
      leadership:'通过知识和所建立的质量标准来领导。通过技术掌握激励他人。可能难以给予没有监督的自主权。在创建流程、标准和控制方面表现出色，能提升整个团队的质量。',
      conflict:'偏好用逻辑论点和数据解决——情感不能说服他们，反而让他们不适。可能将批评个人化，即使是纯粹专业的批评。在公开冲突中，倾向于封闭自我、独自处理并避免直接对抗。',
      motivators:['对专业知识和技术能力的认可','自主以正确方式完成工作，不受走捷径的压力','有明确流程和高标准的有序环境','需要深度的智识复杂挑战'],
      demotivators:['在没有质量的情况下交付的压力——"完成胜于完美"','没有充分依据或基于纯直觉的决策','肤浅的工作和不关心细节的同事','没有一致逻辑解释的流程变更'],
      blindSpots:['分析瘫痪：可能因无法停止完善而延迟交付。','难以接受"现在足够好"有时胜过"完美但迟到"。','可能对质量标准不同的同事做出负面判断——产生摩擦。','对细节的过度关注可能导致失去对更大影响和战略背景的视野。'],
    },
  },
};

// Secondary profile combination texts
const secondaryComboText = {
  pt: { DI:'une força de execução com capacidade de influenciar e engajar — liderança de alto impacto.', DC:'combina velocidade de decisão com rigor analítico — exigente consigo e com o time.', DS:'equilibra assertividade com sensibilidade às relações — liderança mais humana.', ID:'combina entusiasmo com orientação a resultados — perfil forte em vendas e liderança.', IS:'une comunicação com cuidado genuíno com as pessoas — muito eficaz em RH, CS e cultura.', IC:'equilibra criatividade com rigor — perfil raro e versátil.', SI:'une estabilidade com comunicação — naturalmente harmonioso e empático.', SC:'combina consistência com precisão — entrega metódica e confiável.', SD:'equilibra paciência com assertividade quando necessário.', CD:'combina análise profunda com orientação à ação — evita a paralisia por análise.', CS:'une precisão com cuidado interpessoal — analista que também sabe ouvir.', CI:'equilibra rigor com comunicação — transforma análise complexa em mensagem acessível.' },
  en: { DI:'combines execution strength with the ability to influence and engage — high-impact leadership.', DC:'combines decision speed with analytical rigor — demanding of themselves and the team.', DS:'balances assertiveness with relationship sensitivity — more human leadership.', ID:'combines enthusiasm with results orientation — strong in sales and leadership.', IS:'unites communication with genuine care for people — very effective in HR, CS, and culture.', IC:'balances creativity with rigor — a rare and versatile profile.', SI:'unites stability with communication — naturally harmonious and empathetic.', SC:'combines consistency with precision — methodical and reliable delivery.', SD:'balances patience with assertiveness when needed.', CD:'combines deep analysis with action orientation — avoids analysis paralysis.', CS:'unites precision with interpersonal care — an analyst who also knows how to listen.', CI:'balances rigor with communication — transforms complex analysis into accessible messages.' },
  zh: { DI:'将执行力与影响和参与能力相结合——高影响力的领导。', DC:'将决策速度与分析严谨性相结合——对自己和团队都很严格。', DS:'在果断与关系敏感性之间取得平衡——更人性化的领导。', ID:'将热情与成果导向相结合——在销售和领导力方面表现突出。', IS:'将沟通与对人的真诚关怀相结合——在人力资源、客服和文化方面非常有效。', IC:'在创造力与严谨性之间取得平衡——罕见而多才多艺的档案。', SI:'将稳定性与沟通能力相结合——天然和谐、富有同理心。', SC:'将一致性与精确性相结合——有条不紊、可靠的交付。', SD:'在必要时在耐心与果断之间取得平衡。', CD:'将深度分析与行动导向相结合——避免分析瘫痪。', CS:'将精确性与人际关怀相结合——懂得倾听的分析师。', CI:'在严谨与沟通之间取得平衡——将复杂分析转化为易懂的信息。' },
};

// ── HTML helpers ──────────────────────────────────────────────────────────────
function sec(icon, text) {
  return `<div style="font-size:10px;font-weight:700;color:#374151;text-transform:uppercase;letter-spacing:.06em;margin-bottom:8px;padding-bottom:5px;border-bottom:1px solid #E5E7EB">${icon} ${text}</div>`;
}

function scoreBar(value, color, label) {
  return `<div style="margin-bottom:9px">
    <div style="font-size:10px;color:#6B7280;font-weight:600;margin-bottom:2px">${label}</div>
    <div style="display:flex;align-items:center;gap:8px">
      <div style="flex:1;height:7px;background:#E5E7EB;border-radius:99px;overflow:hidden">
        <div style="width:${value}%;height:100%;background:${color};border-radius:99px"></div>
      </div>
      <span style="font-weight:800;font-size:13px;color:${color};width:36px">${value}%</span>
    </div>
  </div>`;
}

function discBar(label, value, color) {
  return `<div style="margin-bottom:7px">
    <div style="display:flex;justify-content:space-between;margin-bottom:2px">
      <span style="font-size:10px;color:#6B7280;font-weight:600">${label}</span>
      <span style="font-size:10px;font-weight:700;color:${color}">${value}%</span>
    </div>
    <div style="height:5px;background:#F3F4F6;border-radius:99px;overflow:hidden">
      <div style="width:${value}%;height:100%;background:${color};border-radius:99px"></div>
    </div>
  </div>`;
}

// ── Main export ───────────────────────────────────────────────────────────────
export function generatePDF(candidate, job, lang = 'pt') {
  const lbl        = L[lang] || L.pt;
  const ai         = candidate.aiAnalysis || {};
  const disc       = candidate.disc || {};
  const profile    = disc.profile || 'S';
  const discC      = discColors[profile] || discColors.S;
  const discScores = disc.scores || { D:25, I:25, S:25, C:25 };
  const recStyle   = recColors[ai.recommendation] || recColors.recommended_with_caveats;
  const seniority  = (seniorityI18n[lang] || seniorityI18n.pt)[ai.seniority] || ai.seniority || '—';

  // Select DISC content in correct language
  const pd = lang === 'pt'
    ? discProfiles[profile]
    : (discContentI18n[lang] || discContentI18n.en)[profile];
  if (!pd) return;

  const locale = lang === 'pt' ? 'pt-BR' : lang === 'zh' ? 'zh-CN' : 'en-US';
  const today  = new Date().toLocaleDateString(locale);

  // Secondary profile
  const secondaryKey = Object.entries(discScores)
    .filter(([k]) => k !== profile).sort(([,a],[,b]) => b-a)[0]?.[0];
  const showSecondary = secondaryKey && discScores[secondaryKey] >= 25;
  const secC = secondaryKey ? discColors[secondaryKey] : null;
  const secP = secondaryKey
    ? (lang === 'pt' ? discProfiles[secondaryKey] : (discContentI18n[lang] || discContentI18n.en)[secondaryKey])
    : null;

  // Pick the correct language version of text fields, falling back to PT
  const pickLang = (ptVal, enVal, zhVal) => {
    if (lang === 'en' && enVal) return enVal;
    if (lang === 'zh' && zhVal) return zhVal;
    return ptVal;
  };
  const pickArr = (ptArr, enArr, zhArr) => {
    if (lang === 'en' && enArr?.length) return enArr;
    if (lang === 'zh' && zhArr?.length) return zhArr;
    return ptArr || [];
  };

  const strengths = pickArr(ai.strengths, ai.strengthsEn, ai.strengthsZh);
  const gaps      = pickArr(ai.gaps,      ai.gapsEn,      ai.gapsZh);
  const risks     = pickArr(ai.risks,     ai.risksEn,     ai.risksZh);
  const qualSummary = pickLang(ai.qualitativeSummary, ai.qualitativeSummaryEn, ai.qualitativeSummaryZh);

  const stageMap = stageI18n[lang] || {};
  const lnMap    = langNameI18n[lang] || {};
  const lvMap    = langLevelI18n[lang] || {};

  const commentsHtml = (candidate.interviewComments || []).map(c => {
    const obs = pickLang(c.observation, c.observationEn, c.observationZh);
    return `
    <div style="padding:8px 11px;background:#F9FAFB;border-radius:7px;margin-bottom:6px;border-left:3px solid #4F46E5;break-inside:avoid;page-break-inside:avoid">
      <div style="font-size:9px;color:#6B7280;margin-bottom:2px">${stageMap[c.stage] || c.stage} · ${c.interviewer} · ${c.date}</div>
      <div style="font-size:11px;color:#374151;line-height:1.5">${obs}</div>
    </div>`;
  }).join('');

  const languagesHtml = (candidate.languages || []).map(l => {
    const notes = pickLang(l.notes, l.notesEn, l.notesZh);
    return `<div style="display:inline-flex;flex-direction:column;margin:2px 3px 2px 0;vertical-align:top">
      <span style="display:inline-block;padding:3px 9px;background:#EEF2FF;color:#4F46E5;border-radius:99px;font-size:10px;font-weight:700">${lnMap[l.language] || l.language} — ${lvMap[l.level] || l.level}</span>
      ${notes ? `<span style="font-size:9px;color:#6B7280;margin-top:2px;padding:0 4px">${notes}</span>` : ''}
    </div>`;
  }).join('');

  // DISC page builders
  const behaviorsHtml = (pd.behaviors || []).map(b => `
    <div style="display:flex;gap:9px;padding:9px 11px;background:${discC.bg};border-radius:7px;border-left:3px solid ${discC.color};margin-bottom:7px;break-inside:avoid;page-break-inside:avoid">
      <span style="font-size:15px;flex-shrink:0;line-height:1.35">${b.icon}</span>
      <div>
        <div style="font-size:10px;font-weight:700;color:${discC.color};margin-bottom:2px">${b.title}</div>
        <div style="font-size:11px;color:#374151;line-height:1.55">${b.text}</div>
      </div>
    </div>`).join('');

  const commTipsHtml = (pd.communication?.tips || []).map(t =>
    `<div style="display:flex;gap:5px;font-size:10px;color:#4B5563;line-height:1.5;margin-bottom:4px;break-inside:avoid;page-break-inside:avoid"><span style="color:${discC.color};font-weight:700;flex-shrink:0">→</span>${t}</div>`
  ).join('');

  const motivatorsHtml = (pd.motivators || []).map(m =>
    `<div style="padding:6px 9px;background:#F0FDF4;border-radius:5px;border-left:2px solid #16A34A;font-size:10px;color:#14532D;line-height:1.4;margin-bottom:4px;break-inside:avoid;page-break-inside:avoid">${m}</div>`
  ).join('');

  const demotivatorsHtml = (pd.demotivators || []).map(d =>
    `<div style="padding:6px 9px;background:#FEF2F2;border-radius:5px;border-left:2px solid #DC2626;font-size:10px;color:#7F1D1D;line-height:1.4;margin-bottom:4px;break-inside:avoid;page-break-inside:avoid">${d}</div>`
  ).join('');

  const blindSpotsHtml = (pd.blindSpots || []).map(b =>
    `<div style="display:flex;gap:7px;padding:7px 10px;background:#FFFBEB;border-radius:5px;border-left:2px solid #F59E0B;margin-bottom:5px;break-inside:avoid;page-break-inside:avoid">
      <span style="color:#D97706;font-weight:700;flex-shrink:0;font-size:11px">!</span>
      <span style="font-size:10px;color:#78350F;line-height:1.5">${b}</span>
    </div>`
  ).join('');

  const comboKey = secondaryKey ? `${profile}${secondaryKey}` : '';
  const comboText = (secondaryComboText[lang] || secondaryComboText.pt)[comboKey] || '';

  const secondaryHtml = showSecondary && secC && secP ? `
    <div style="margin-top:14px;padding:11px 13px;background:${secC.bg};border-radius:8px;border-left:3px solid ${secC.color};break-inside:avoid;page-break-inside:avoid">
      <div style="font-size:10px;font-weight:700;color:${secC.color};text-transform:uppercase;letter-spacing:.05em;margin-bottom:4px">
        ${secC.emoji} ${lbl.discSecondary} — ${secP.title || ''} (${secondaryKey}: ${discScores[secondaryKey]}%)
      </div>
      <div style="font-size:11px;color:#374151;line-height:1.6">
        ${lang === 'pt'
          ? `Com ${discScores[secondaryKey]}% de ${secP.label || ''}, este candidato também carrega traços de <strong>${secP.title || ''}</strong>. Essa combinação <strong>${profile}${secondaryKey}</strong> tende a ${comboText}`
          : lang === 'zh'
          ? `该候选人${secondaryKey}得分为${discScores[secondaryKey]}%，同时具有<strong>${secP.title || ''}</strong>的特质。<strong>${profile}${secondaryKey}</strong>组合倾向于${comboText}`
          : `With ${discScores[secondaryKey]}% in ${secP.title || ''}, this candidate also carries traits of a <strong>${secP.title || ''}</strong>. The <strong>${profile}${secondaryKey}</strong> combination tends to ${comboText}`
        }
      </div>
    </div>` : '';

  // ── HTML ─────────────────────────────────────────────────────────────────────
  const html = `<!DOCTYPE html>
<html lang="${lang==='zh'?'zh-CN':lang==='en'?'en':'pt-BR'}">
<head>
<meta charset="UTF-8">
<title>${lbl.executiveReport} — ${candidate.name}</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:-apple-system,'Helvetica Neue',Arial,'Noto Sans CJK SC',sans-serif;color:#1F2937;background:white;-webkit-print-color-adjust:exact;print-color-adjust:exact}
  @page{size:A4;margin:13mm 14mm 16mm}
  .no-break{break-inside:avoid;page-break-inside:avoid}
  .page-break{break-before:page;page-break-before:always}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:11px}
  .grid3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:9px}
  .box{background:#F9FAFB;border-radius:7px;padding:8px 10px}
  .box-label{font-size:9px;color:#9CA3AF;font-weight:600;text-transform:uppercase;letter-spacing:.04em;margin-bottom:2px}
  .box-value{font-size:11px;font-weight:600;color:#111827}
  .section{margin-bottom:15px}
  .footer{margin-top:18px;padding-top:7px;border-top:1px solid #E5E7EB;display:flex;justify-content:space-between;align-items:center}
</style>
</head>
<body>

<!-- PAGE 1 -->
<div>
  <div class="no-break" style="display:flex;align-items:center;justify-content:space-between;margin-bottom:15px;padding-bottom:11px;border-bottom:3px solid #1B5299">
    <div>
      <div style="font-size:8px;color:#9CA3AF;letter-spacing:.1em;text-transform:uppercase;margin-bottom:3px">${lbl.confidential}</div>
      <div style="font-size:21px;font-weight:800;color:#111827">${candidate.name}</div>
      <div style="font-size:12px;color:#4F46E5;font-weight:600;margin-top:2px">${job?.title||'—'} · ${job?.department||''}</div>
    </div>
    <div style="text-align:right">
      ${logoHtml()}
      <div style="font-size:9px;color:#9CA3AF;margin-top:4px">${lbl.executiveReport} · ${today}</div>
    </div>
  </div>

  <div class="no-break section" style="padding:11px 15px;background:${recStyle.bg};border:1.5px solid ${recStyle.border};border-radius:9px">
    <div style="display:flex;align-items:center;justify-content:space-between">
      <div>
        <div style="font-size:8px;color:${recStyle.color};font-weight:700;text-transform:uppercase;letter-spacing:.06em;margin-bottom:2px">${lbl.recommendation}</div>
        <div style="font-size:16px;font-weight:800;color:${recStyle.color}">${lbl.recLabels[ai.recommendation]||'—'}</div>
      </div>
      <div style="display:flex;gap:20px;text-align:center">
        <div><div style="font-size:26px;font-weight:900;color:#4F46E5;line-height:1">${ai.technicalScore??'—'}%</div><div style="font-size:8px;color:#6B7280;font-weight:600;margin-top:1px">${lbl.technical}</div></div>
        <div><div style="font-size:26px;font-weight:900;color:#10B981;line-height:1">${ai.behavioralScore??'—'}%</div><div style="font-size:8px;color:#6B7280;font-weight:600;margin-top:1px">${lbl.behavioral}</div></div>
      </div>
    </div>
  </div>

  ${qualSummary?`
  <div class="no-break section">
    ${sec('📋',lbl.summary)}
    <div style="padding:10px 13px;background:#EEF2FF;border-radius:7px;border-left:3px solid #4F46E5;font-size:11px;color:#374151;line-height:1.7">${qualSummary}</div>
  </div>`:''}

  ${(strengths.length||gaps.length)?`
  <div class="grid2 section">
    <div class="no-break">
      ${sec('✅',lbl.strengths)}
      ${strengths.map(s=>`<div style="padding:6px 9px;background:#F0FDF4;border-radius:5px;border-left:2px solid #16A34A;font-size:10px;color:#14532D;line-height:1.45;margin-bottom:4px;break-inside:avoid;page-break-inside:avoid">${s}</div>`).join('')}
    </div>
    <div class="no-break">
      ${sec('⚠️',lbl.gaps)}
      ${gaps.map(g=>`<div style="padding:6px 9px;background:#FFFBEB;border-radius:5px;border-left:2px solid #F59E0B;font-size:10px;color:#78350F;line-height:1.45;margin-bottom:4px;break-inside:avoid;page-break-inside:avoid">${g}</div>`).join('')}
    </div>
  </div>`:''}

  ${risks.length?`
  <div class="no-break section">
    ${sec('🚨',lbl.risks)}
    <div style="background:#FEF2F2;border:1px solid #FEE2E2;border-radius:7px;padding:9px 12px">
      ${risks.map(r=>`<div style="font-size:10px;color:#7F1D1D;margin-bottom:3px;padding-left:9px;border-left:2px solid #FCA5A5;line-height:1.45;break-inside:avoid;page-break-inside:avoid">${r}</div>`).join('')}
    </div>
  </div>`:''}

  <div class="no-break section">
    ${sec('👤',lbl.candidateData)}
    <div class="grid3">
      <div class="box"><div class="box-label">${lbl.email}</div><div class="box-value" style="font-size:9px">${candidate.email||'—'}</div></div>
      <div class="box"><div class="box-label">${lbl.whatsapp}</div><div class="box-value">${candidate.whatsapp||'—'}</div></div>
      <div class="box"><div class="box-label">${lbl.city}</div><div class="box-value">${candidate.city||'—'}</div></div>
      <div class="box"><div class="box-label">${lbl.salary}</div><div class="box-value">${candidate.salaryClaim||'—'}</div></div>
      <div class="box"><div class="box-label">${lbl.availability}</div><div class="box-value">${candidate.startAvailability||'—'}</div></div>
      <div class="box"><div class="box-label">${lbl.seniority}</div><div class="box-value">${seniority}</div></div>
      ${candidate.linkedin && candidate.linkedin !== 'https://www.linkedin.com/in/' ? `<div class="box" style="grid-column:1/-1"><div class="box-label">${lbl.linkedin}</div><div class="box-value"><a href="${candidate.linkedin}" style="color:#0A66C2;font-size:9px;word-break:break-all">${candidate.linkedin}</a></div></div>` : ''}
    </div>
  </div>

  ${languagesHtml?`<div class="no-break section">${sec('🌐',lbl.languages)}<div>${languagesHtml}</div></div>`:''}
  ${commentsHtml?`<div class="section">${sec('💬',lbl.comments)}${commentsHtml}</div>`:''}

  <div class="footer">
    ${logoHtml()}
    <span style="font-size:8px;color:#D1D5DB">${lbl.generatedBy} · ${today}</span>
    <span style="font-size:8px;color:#D1D5DB">${lbl.page} 1 ${lbl.of} 2</span>
  </div>
</div>

<!-- PAGE 2 — DISC -->
<div class="page-break">
  <div class="no-break" style="display:flex;align-items:center;justify-content:space-between;margin-bottom:15px;padding-bottom:11px;border-bottom:3px solid ${discC.color}">
    <div>
      <div style="font-size:8px;color:#9CA3AF;letter-spacing:.08em;text-transform:uppercase;margin-bottom:3px">${candidate.name} · ${job?.title||'—'}</div>
      <div style="font-size:17px;font-weight:800;color:${discC.color}">${discC.emoji} ${lbl.discProfile}</div>
      <div style="font-size:11px;color:#6B7280;margin-top:2px">${pd.title} (${profile}) — ${pd.subtitle}</div>
    </div>
    <div style="text-align:right">${logoHtml()}</div>
  </div>

  <div class="grid2 no-break section">
    <div>
      <div style="padding:11px 13px;background:${discC.bg};border-radius:8px;border-left:4px solid ${discC.color};margin-bottom:9px">
        <div style="font-size:12px;font-weight:700;color:${discC.color};margin-bottom:2px">${discC.emoji} ${pd.title}</div>
        <div style="font-size:10px;color:#6B7280">${pd.subtitle}</div>
      </div>
      <div style="font-size:11px;color:#374151;line-height:1.65;margin-bottom:8px">${pd.summary||''}</div>
      <div style="display:flex;flex-wrap:wrap;gap:3px">
        ${(pd.strengths||[]).map(s=>`<span style="padding:2px 7px;background:${discC.bg};color:${discC.color};border-radius:99px;font-size:9px;font-weight:700">${s}</span>`).join('')}
      </div>
    </div>
    <div>
      ${discBar(lbl.dominance, discScores.D||0, '#EF4444')}
      ${discBar(lbl.influence, discScores.I||0, '#F59E0B')}
      ${discBar(lbl.stability, discScores.S||0, '#10B981')}
      ${discBar(lbl.conformity, discScores.C||0, '#3B82F6')}
    </div>
  </div>

  <div class="section">
    ${sec('🎭', lbl.discBehaviors)}
    ${behaviorsHtml}
  </div>

  <div class="grid2 section">
    <div>
      ${sec('💬', lbl.discCommunication)}
      <div style="font-size:11px;color:#374151;line-height:1.6;margin-bottom:7px">${pd.communication?.style||''}</div>
      ${commTipsHtml}
    </div>
    <div>
      ${sec('👑', lbl.discLeadership)}
      <div style="font-size:11px;color:#374151;line-height:1.6;margin-bottom:12px">${pd.leadership||''}</div>
      ${sec('⚖️', lbl.discConflict)}
      <div style="font-size:11px;color:#374151;line-height:1.6">${pd.conflict||''}</div>
    </div>
  </div>

  <div class="grid2 section">
    <div>
      ${sec('✅', lbl.discMotivators)}
      ${motivatorsHtml}
    </div>
    <div>
      ${sec('🚫', lbl.discDemotivators)}
      ${demotivatorsHtml}
    </div>
  </div>

  ${blindSpotsHtml?`
  <div class="section">
    ${sec('⚠️', lbl.discBlindSpots)}
    ${blindSpotsHtml}
  </div>`:''}

  ${secondaryHtml}

  <div class="footer">
    ${logoHtml()}
    <span style="font-size:8px;color:#D1D5DB">${lbl.generatedBy} · ${today}</span>
    <span style="font-size:8px;color:#D1D5DB">${lbl.page} 2 ${lbl.of} 2</span>
  </div>
</div>

</body>
</html>`;

  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(html);
  win.document.close();
  setTimeout(() => win.print(), 900);
}
